safe: true
pygments: true
lsi: false
exclude: README.md localServer.sh

url: http://cloderic.github.com/
#url: http://www.crowdscontrol.net/

name: Crowds control
tagline: Intermitent AI, virtual humans, 3D and development stuffs
author: Clodéric Mars
mail: cloderic.mars@gmail.com

permalink: /blog/:year-:month-:day-:title