title: Clodéric Mars personal landing page
email: cloderic.mars@gmail.com
description: >
  Personal landing page for Clodéric Mars - CTO @ craft ai
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.crowdscontrol.net"
twitter_username: cloderic
github_username: cloderic

# Build settings
markdown: kramdown
gems:
  - jekyll-redirect-from

# 3rd party services
ga_tracking_code: UA-3838411-6