title: Clodéric Mars
email: cloderic.mars@gmail.com
description: >
  Personal landing page for Clodéric Mars - CTO @ craft ai
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cloderic.com"
twitter_username: cloderic
github_username: cloderic

# Build settings
markdown: kramdown
gems:
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
