safe: true
pygments: true
lsi: true
exclude: README.md localServer.sh project.chproj

url: http://www.crowdscontrol.net

name: Crowds Control
tagline: Artificially intelligent, virtually real
author: Clodéric Mars
mail: cloderic.mars@gmail.com
gravatar: 60ff8db3de74fdd9c6d1313f2f4965de
disqus: "crowdscontrol"

analytics: true

feeds:
  rss: /feeds/rss.xml
  atom: /feeds/atom.xml

colors:
  light: "#f2f2f2"
  dark: "#212121"
  shadow: "#373737"
  primary: "#0090ff"
  primary_shadow: "#43adff"
  secondary: "#ffb300"
  secondary_shadow: "#d99800"

tag_descriptors:
  - tag: navigation
    title: Navigation
  - tag: conference
    title: Conferences

permalink: /blog/:year-:month-:day-:title