[build]
command = "npm run build"
publish = ".next"

[build.environment]
# set TERM variable for terminal output
TERM = "xterm"

# Include all files in all functions
[functions]
included_files = ["app/**"]
